# 기본 공통 설정
server:
  port: 8080

spring:
  application:
    name: BeStudyApplication

logging:
  level:
    root: info
    org.springframework: info
    com.example.be_study: debug

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${GOOGLE_SMTP_ID}
  password: ${GOOGLE_SMTP_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

# Local 프로필
---
spring:
  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/house?useSSL=false&allowPublicKeyRetrieval=true
    username: bestudy
    password: bestudy

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: false
    outOfOrder: true

  application:
    name: BeStudyApplication

logging:
  level:
    root: info

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}

aws:
  accessKey: test
  secretKey: test
  region: ap-northeast-2
  s3:
    baseUrl: http://localhost:4566

server:
  port: 8080

redis:
  host: localhost
  port: 6379

# prod 프로필
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/house?useSSL=false&allowPublicKeyRetrieval=true
    username: bestudy
    password: bestudy

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 60a924edb10f7e39450411a48e2a588d
            client-secret: yqhN4Wtk2jUsV1wE1xawkJ9IgX6g7JlQ
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_image
              - profile_nickname
              - account_email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: false
    outOfOrder: true
